import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    "getting-started",
    "theming",
    {
      type: "category",
      label: "Components",
      collapsible: true,
      items: [
        "components/container",
        "components/box",
        "components/stack",
        "components/text",
        "components/spacer",
        "components/divider",
        "components/button",
        "components/input",
        "components/text-area",
        "components/checkbox",
        "components/switch",
        "components/radio-group",
        "components/select",
        "components/slider",
        "components/otp-input",
        "components/date-picker",
        "components/masked-input",
        "components/tag-input",
        "components/stepper-input",
        "components/search-input",
      ],
    },
  ],
};

export default sidebars;
